export const ORDER_FILTER = "ORDER_FILTER";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_CURRENT_PAGE_TEAMS = "SET_CURRENT_PAGE_TEAMS"
export const SET_CURRENT_PATH = "SET_CURRENT_PATH"